spring.application.name=ms-usuarios
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8080/eureka

spring.datasource.url=jdbc:mysql://localhost:3307/bd_usuarios
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mi_clave_super_segura_para_firmar_tokens_2026
jwt.expiration=3600000