CREATE DATABASE IF NOT EXISTS bd_usuarios;
CREATE DATABASE IF NOT EXISTS bd_libros;
CREATE DATABASE IF NOT EXISTS bd_ordenes;
CREATE DATABASE IF NOT EXISTS bd_prestamos;
CREATE DATABASE IF NOT EXISTS bd_pagos;